//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "bolaxbase.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_nav_pier_m_F" createvehicle [4104.00878906,5706.418945,0.100616];
_obj setposATL [4104.00878906,5706.418945,0.100616];
_obj setdir 124.754;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Pier_F" createvehicle [4123.0610352,5699.251953,5.14117];
_obj setposATL [4123.0610352,5699.251953,5.14117];
_obj setdir 34.947;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Pier_F" createvehicle [4114.48291,5687.012207,11.621];
_obj setposATL [4114.48291,5687.012207,11.621];
_obj setdir 34.947;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_MilOffices_V1_F" createvehicle [3765.899902,18854.5,2.38419e-007];
_obj setposATL [3765.899902,18854.5,2.38419e-007];
_obj setdir 1.186;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Pier_F" createvehicle [4130.756348,5710.270508,0.0276337];
_obj setposATL [4130.756348,5710.270508,0.0276337];
_obj setdir 33.856;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4095.153076,5723.973633,-0.166519];
_obj setposATL [4095.153076,5723.973633,-0.166519];
_obj setdir 290.931;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4103.87207,5712.905762,-0.050705];
_obj setposATL [4103.87207,5712.905762,-0.050705];
_obj setdir 221.466;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4103.0126953,5742.548828,0.0215454];
_obj setposATL [4103.0126953,5742.548828,0.0215454];
_obj setdir 306.825;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4100.79541,5738.415527,-0.351089];
_obj setposATL [4100.79541,5738.415527,-0.351089];
_obj setdir 289.764;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4114.706055,5747.829102,0.0149384];
_obj setposATL [4114.706055,5747.829102,0.0149384];
_obj setdir 9.189;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4110.102051,5748.387695,0.0149384];
_obj setposATL [4110.102051,5748.387695,0.0149384];
_obj setdir 9.189;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4124.515137,5746.604004,0.0562439];
_obj setposATL [4124.515137,5746.604004,0.0562439];
_obj setdir 6.444;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4119.533203,5747.181641,0.0149384];
_obj setposATL [4119.533203,5747.181641,0.0149384];
_obj setdir 9.189;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4134.544434,5744.415039,-0.0305481];
_obj setposATL [4134.544434,5744.415039,-0.0305481];
_obj setdir 19.186;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4129.612305,5745.785645,0.0711823];
_obj setposATL [4129.612305,5745.785645,0.0711823];
_obj setdir 11.882;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4143.845703,5742.991211,-0.0793304];
_obj setposATL [4143.845703,5742.991211,-0.0793304];
_obj setdir 11.2;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-9.892,-9.892] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4139.0986328,5743.859863,-0.0397186];
_obj setposATL [4139.0986328,5743.859863,-0.0397186];
_obj setdir 12.072;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-9.334,-9.334] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4166.427734,5729.625488,-0.327881];
_obj setposATL [4166.427734,5729.625488,-0.327881];
_obj setdir 116.715;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4160.408691,5736.200195,0.0149384];
_obj setposATL [4160.408691,5736.200195,0.0149384];
_obj setdir 22.319;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4165.113281,5733.599121,0.0149384];
_obj setposATL [4165.113281,5733.599121,0.0149384];
_obj setdir 32.186;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4099.993652,5716.436523,-0.050705];
_obj setposATL [4099.993652,5716.436523,-0.050705];
_obj setdir 221.466;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4096.147461,5719.328613,-0.050705];
_obj setposATL [4096.147461,5719.328613,-0.050705];
_obj setdir 221.466;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4097.0273438,5728.813477,-0.209518];
_obj setposATL [4097.0273438,5728.813477,-0.209518];
_obj setdir 293.121;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4106.0825195,5746.682617,0];
_obj setposATL [4106.0825195,5746.682617,0];
_obj setdir 301.728;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4098.900879,5733.598145,-0.209518];
_obj setposATL [4098.900879,5733.598145,-0.209518];
_obj setdir 289.98;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4100.0610352,5716.42627,3.44392];
_obj setposATL [4100.0610352,5716.42627,3.44392];
_obj setdir 221.466;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4096.426758,5719.637695,3.44655];
_obj setposATL [4096.426758,5719.637695,3.44655];
_obj setdir 221.466;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4105.257813,5715.330566,2.53729];
_obj setposATL [4105.257813,5715.330566,2.53729];
_obj setdir 303.561;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall1_F" createvehicle [4102.814453,5714.769043,3.12534];
_obj setposATL [4102.814453,5714.769043,3.12534];
_obj setdir 40.371;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall1_F" createvehicle [4103.756836,5713.979004,3.12534];
_obj setposATL [4103.756836,5713.979004,3.12534];
_obj setdir 40.371;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4108.143066,5719.645508,1.20563];
_obj setposATL [4108.143066,5719.645508,1.20563];
_obj setdir 303.952;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Pier_F" createvehicle [4137.846191,5721.0332031,-2.64828];
_obj setposATL [4137.846191,5721.0332031,-2.64828];
_obj setdir 34.033;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4164.40332,5724.925293,-0.125763];
_obj setposATL [4164.40332,5724.925293,-0.125763];
_obj setdir 113.813;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4163.0615234,5722.015625,-0.0921326];
_obj setposATL [4163.0615234,5722.015625,-0.0921326];
_obj setdir 118.343;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4161.203613,5718.845703,-0.387955];
_obj setposATL [4161.203613,5718.845703,-0.387955];
_obj setdir 123.818;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4158.587402,5714.805176,0.0589447];
_obj setposATL [4158.587402,5714.805176,0.0589447];
_obj setdir 121.881;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4156.216309,5741.830078,0.217377];
_obj setposATL [4156.216309,5741.830078,0.217377];
_obj setdir 292.233;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-4.309,-4.309] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4147.475586,5745.20166,0.16095];
_obj setposATL [4147.475586,5745.20166,0.16095];
_obj setdir 281.221;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-6.887,-6.887] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4157.249023,5748.00488281,0.270264];
_obj setposATL [4157.249023,5748.00488281,0.270264];
_obj setdir 261.107;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,3.506,3.506] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4149.050293,5752.0620117,0.177353];
_obj setposATL [4149.050293,5752.0620117,0.177353];
_obj setdir 283.389;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-6.782,-6.782] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4157.925293,5754.387695,0.223526];
_obj setposATL [4157.925293,5754.387695,0.223526];
_obj setdir 292.251;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-3.845,-3.845] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4156.836426,5737.543457,0.0149384];
_obj setposATL [4156.836426,5737.543457,0.0149384];
_obj setdir 22.319;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4149.327637,5758.858398,0.220535];
_obj setposATL [4149.327637,5758.858398,0.220535];
_obj setdir 81.749;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,4.179,4.179] call BIS_fnc_setPitchBank;
_obj = "Land_Slide_F" createvehicle [4111.705566,5739.426758,-0.160706];
_obj setposATL [4111.705566,5739.426758,-0.160706];
_obj setdir 51.467;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [1822.400024,5622.359863,0];
_obj setposATL [1822.400024,5622.359863,0];
_obj setdir 294.079;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [1824.588379,5627.256836,0];
_obj setposATL [1824.588379,5627.256836,0];
_obj setdir 294.079;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [1828.965088,5637.0507813,0];
_obj setposATL [1828.965088,5637.0507813,0];
_obj setdir 294.079;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [1826.776733,5632.153809,0];
_obj setposATL [1826.776733,5632.153809,0];
_obj setdir 294.079;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [1831.153442,5641.947754,0];
_obj setposATL [1831.153442,5641.947754,0];
_obj setdir 294.079;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [1833.341797,5646.844727,0];
_obj setposATL [1833.341797,5646.844727,0];
_obj setdir 294.079;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_i_Garage_V1_F" createvehicle [4106.11377,5722.972168,1.39349];
_obj setposATL [4106.11377,5722.972168,1.39349];
_obj setdir 123.75;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_nav_pier_m_F" createvehicle [4148.378906,5713.547852,-25.9332];
_obj setposATL [4148.378906,5713.547852,-25.9332];
_obj setdir 35.194;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,14.816,14.816] call BIS_fnc_setPitchBank;
_obj = "Land_nav_pier_m_F" createvehicle [4164.402832,5685.308105,11.6075];
_obj setposATL [4164.402832,5685.308105,11.6075];
_obj setdir 34.234;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-0.282,-0.282] call BIS_fnc_setPitchBank;
_obj = "Land_Pier_F" createvehicle [4176.0673828,5682.379395,21.9916];
_obj setposATL [4176.0673828,5682.379395,21.9916];
_obj setdir 303.359;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4095.858643,5688.0786133,16.3829];
_obj setposATL [4095.858643,5688.0786133,16.3829];
_obj setdir 215.511;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Ancient_Wall_4m_F" createvehicle [4036.540039,5450.169922,0];
_obj setposATL [4036.540039,5450.169922,0];
_obj setdir 174.565;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4091.631104,5691.0419922,15.7775];
_obj setposATL [4091.631104,5691.0419922,15.7775];
_obj setdir 215.511;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4099.989258,5685.0161133,16.9717];
_obj setposATL [4099.989258,5685.0161133,16.9717];
_obj setdir 215.511;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4104.0722656,5682.116699,17.4457];
_obj setposATL [4104.0722656,5682.116699,17.4457];
_obj setdir 215.511;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4108.347656,5679.124023,17.9394];
_obj setposATL [4108.347656,5679.124023,17.9394];
_obj setdir 215.511;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4112.439941,5676.164063,18.2205];
_obj setposATL [4112.439941,5676.164063,18.2205];
_obj setdir 215.205;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4116.797363,5673.226074,18.6803];
_obj setposATL [4116.797363,5673.226074,18.6803];
_obj setdir 215.555;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4120.692871,5670.416504,19.3663];
_obj setposATL [4120.692871,5670.416504,19.3663];
_obj setdir 215.48;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4123.524414,5668.541504,20.0461];
_obj setposATL [4123.524414,5668.541504,20.0461];
_obj setdir 215.48;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4090.942871,5694.977051,13.9803];
_obj setposATL [4090.942871,5694.977051,13.9803];
_obj setdir 303.448;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4093.806152,5699.393066,11.0551];
_obj setposATL [4093.806152,5699.393066,11.0551];
_obj setdir 303.186;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4096.697266,5703.661133,8.2661];
_obj setposATL [4096.697266,5703.661133,8.2661];
_obj setdir 303.186;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Ancient_Wall_4m_F" createvehicle [3367.649902,6002.830078,0.154578];
_obj setposATL [3367.649902,6002.830078,0.154578];
_obj setdir 286.205;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4099.516113,5707.903809,5.67947];
_obj setposATL [4099.516113,5707.903809,5.67947];
_obj setdir 303.264;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4101.999023,5711.623047,3.71889];
_obj setposATL [4101.999023,5711.623047,3.71889];
_obj setdir 303.915;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4127.444824,5669.223145,19.8598];
_obj setposATL [4127.444824,5669.223145,19.8598];
_obj setdir 124.978;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4130.378418,5673.452148,18.3547];
_obj setposATL [4130.378418,5673.452148,18.3547];
_obj setdir 124.728;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4133.291992,5677.722656,16.8179];
_obj setposATL [4133.291992,5677.722656,16.8179];
_obj setdir 124.731;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4136.175781,5681.96582,15.3187];
_obj setposATL [4136.175781,5681.96582,15.3187];
_obj setdir 124.14;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4141.905762,5690.272461,12.1417];
_obj setposATL [4141.905762,5690.272461,12.1417];
_obj setdir 124.537;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4139.0253906,5686.100586,13.7811];
_obj setposATL [4139.0253906,5686.100586,13.7811];
_obj setdir 124.537;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4142.979492,5691.754883,11.4985];
_obj setposATL [4142.979492,5691.754883,11.4985];
_obj setdir 125.181;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4155.834961,5710.592773,1.8293];
_obj setposATL [4155.834961,5710.592773,1.8293];
_obj setdir 123.893;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4152.962402,5706.27002,3.41087];
_obj setposATL [4152.962402,5706.27002,3.41087];
_obj setdir 123.768;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4150.63623,5702.554199,5.28835];
_obj setposATL [4150.63623,5702.554199,5.28835];
_obj setdir 123.882;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "PortableHelipadLight_01_yellow_F" createvehicle [4107.775879,5705.588379,5.94704];
_obj setposATL [4107.775879,5705.588379,5.94704];
_obj setdir 327.893;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4158.323242,5760.993164,0.174454];
_obj setposATL [4158.323242,5760.993164,0.174454];
_obj setdir 79.001;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-1.709,-1.709] call BIS_fnc_setPitchBank;
_obj = "Land_Cargo_HQ_V1_F" createvehicle [4102.213379,5695.97998,12.2799];
_obj setposATL [4102.213379,5695.97998,12.2799];
_obj setdir 124.491;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_Unfinished_Building_01_F" createvehicle [4128.462402,5736.86084,0.3078];
_obj setposATL [4128.462402,5736.86084,0.3078];
_obj setdir 287.514;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4145.17334,5734.571777,0.0872192];
_obj setposATL [4145.17334,5734.571777,0.0872192];
_obj setdir 269.395;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-8.605,-8.605] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4145.51123,5739.720703,0.107132];
_obj setposATL [4145.51123,5739.720703,0.107132];
_obj setdir 272.848;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-8.364,-8.364] call BIS_fnc_setPitchBank;
_obj = "Land_CncWall4_F" createvehicle [4146.594727,5729.514648,-0.0202179];
_obj setposATL [4146.594727,5729.514648,-0.0202179];
_obj setdir 237.602;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-8.328,-8.328] call BIS_fnc_setPitchBank;
_obj = "Box_East_AmmoOrd_F" createvehicle [4102.736816,5723.901855,0];
_obj setposATL [4102.736816,5723.901855,0];
_obj setdir 29.506;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "B_Respawn_TentDome_F" createvehicle [4412.40332,5224.407715,1417.34];
_obj setposATL [4412.40332,5224.407715,1417.34];
_obj setdir 82.765;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,0,0] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4154.790039,5766.728516,0.395599];
_obj setposATL [4154.790039,5766.728516,0.395599];
_obj setdir 40.937;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-8.799,-8.799] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4145.876465,5764.416016,0.418724];
_obj setposATL [4145.876465,5764.416016,0.418724];
_obj setdir 39.798;
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
[_obj,-4.996,-4.996] call BIS_fnc_setPitchBank;
_obj = "Land_CncBarrierMedium4_F" createvehicle [4144.322266,5768.999512,0.477455];
_obj setVariable ["R3F_LOG_disabled", true, true]; //so you cant steal it =)
