//#include "location1.sqf"
#include "slitchbaseplpha.sqf"
#include "testbase.sqf"
#include "bolaxbase.sqf"
#include "checkpoint.sqf"
#include "pierfix.sqf"
#include "solartower.sqf"
#include "airbasebuildup.sqf"
