//This file was generated by Map Builder
//To load this objects copy this script to your mission and put
// nil = [] execVM "PIERFIX1.sqf";
//in your init.sqf or a trigger-activation.
private["_obj"];
_obj = "Land_WIP_F" createvehicle [2108.725098,1851.869019,3.63005];
_obj setposATL [2108.725098,1851.869019,3.63005];
_obj setVectorDirAndUp [[0.737723,0.675103,0],[0,0,1]];
_obj setposATL [2108.725098,1851.869019,3.63005];
_obj = "Land_Pier_F" createvehicle [2095.34082,1853.854004,2.05966];
_obj setposATL [2095.34082,1853.854004,2.05966];
_obj setVectorDirAndUp [[0.668246,-0.74394,0],[0,-0,1]];
_obj setposATL [2095.34082,1853.854004,2.05966];
_obj = "Land_Pier_F" createvehicle [2115.520508,1831.88855,2.09296];
_obj setposATL [2115.520508,1831.88855,2.09296];
_obj setVectorDirAndUp [[-0.66849,0.743721,0],[0,0,1]];
_obj setposATL [2115.520508,1831.88855,2.09296];
